name: Possibility Hacker
favicon: null
layout_spectrum: 0.348480582004413
typography_spectrum: 0.98063
title: Hacking Possibility since 1979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.060715187108144164
  lightness: 0.7038852539844811
  saturation: 0.8824258840177208
  rhythmicContrast: 0.5796373670455068
purpose: []
